### ISSUE TITLE
Make a request to Ticketmaster API

### ISSUE THREAD

**Issue by ditazan** [ditazan/LocalBeats#3]
- Use the text input from genre and location search bars on page to make a request to TM API
- Text from genre/artist input will plug into Ticketmaster for similar events
- Text from location input will plug into Ticketmaster for nearby events

**Comment by bkfleet1** [comment]
Ticketmaster Category API complete. Returns music genreId and genreName, which we are using to populate the SELECT dropdown on index.html.

**Comment by bkfleet1** [comment]
Completed and pushed to develop branch
